### ISSUE TITLE
trying to use sort on the jetson target, any way to reduce the time of performance?

### ISSUE THREAD

**Issue by YoungjaeDev** [tensorturtle/classy-sort-yolov5#12]
**Sort** takes about 5-9 times more than the yolo5 detect I think it's due to `CPU processing`, 
is there **any way** to reduce it?

Thank you

**Comment by tensorturtle** [comment]
Hi @youngjae-avikus , I totally relate with your issue. I have tried to run it on Jetson.
You are right, SORT is somewhat slow on the CPU. 
If you're willing to sacrifice precision, I recommend [IOUTracker](https://github.com/bochinski/iou-tracker)
[C++ implementations of SORT](https://github.com/yasenh/sort-cpp) are probably faster, but I have not tested these.

**Comment by YoungjaeDev** [comment]
Is DeepSort the same because it is `Feature info + Sort` after all? 
I'm curious about how to attach the tracker at Real time.
Thank you

**Comment by tensorturtle** [comment]
If you're looking for speed, DeepSORT won't help you - it runs a separate neural network on top of the object detection.
Check out [QSORT](https://github.com/developer0hye/qsort), which I think is close to a drop-in replacement for SORT.

**Comment by YoungjaeDev** [comment]
thank you!
I wonder that sort is kf+iou tracker?  Predicting with Kf and doing association with iou, this is how I think. is it right?
I think iou tracker is more faster!

**Comment by tensorturtle** [comment]
@youngjae-avikus Yes your understanding is correct- I suggest you take a look at the code, it's relatively clearly written and commented.
