### ISSUE TITLE
Is tracking possible only with kf while skipping detection?

### ISSUE THREAD

**Issue by YoungjaeDev** [tensorturtle/classy-sort-yolov5#13]
Hello
I would like to estimate the bbox only by tracking to increase the fps, is there anything I can refer to?
Thank you.

**Comment by tensorturtle** [comment]
Yes, you are in luck! Check out
https://github.com/developer0hye/qsort
Although I haven't tested it, I epecr this to be a basicaly in-place faster, less accurate replacement for the SORT tracker.

**Comment by YoungjaeDev** [comment]
@tensorturtle 
Oh, I've tested it (qsort) and it improves by 3-4fps, but in general, the detection seems to take more time than tracking, so I want to skip the detection as the focus

**Comment by jinmc** [comment]
Wow, This is something I've been looking for! Thanks!
