### ISSUE TITLE
Can this code be more gently predicated on the small box size?

### ISSUE THREAD

**Issue by YoungjaeDev** [tensorturtle/classy-sort-yolov5#16]
The small box size seems to be shaking a lot, do you already have a predict in consideration of the box size in the Kalman filter?

**Comment by tensorturtle** [comment]
@youngjae-avikus Unfortunately no, the box area is not a factor in this current implementation.

**Comment by YoungjaeDev** [comment]
@tensorturtle Hi! The results of the experiment showed that in my case, I lowered the variance for bbox prediction and it improved
