### ISSUE TITLE
Error when using v5m6 models with img_size 1280

### ISSUE THREAD

**Issue by OleksiiYeromenko** [tensorturtle/classy-sort-yolov5#3]
Hi,
Thanks for cool work, but I'm receiving error 
`RuntimeError: Sizes of tensors must match except in dimension 1. Got 24 and 23 in dimension 2 (The offending index is 1)`
when trying to run _6 models with image size 1280.

**Comment by OleksiiYeromenko** [comment]
Ok, mistake in `classy_track.py` - line 145 - missing `stride`:
```
 dataset = LoadImages(source, img_size=imgsz)
```

```
dataset = LoadImages(source, img_size=imgsz, stride=stride)
```

**Comment by tensorturtle** [comment]
Hi @OleksiiYeromenko , I'm glad you were able to find the fix. It looks like that argument was added in YOLOV5 version 5.0. This repo is currently based on YOLOV5 version 4.0
