### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Adeel-Intizar** [tensorturtle/classy-sort-yolov5#5]
Hello, i am having issues running this repo
![image](https://user-images.githubusercontent.com/56041154/126064237-1404d2ea-390c-46af-8e38-08ff62d081c8.png)

**Comment by tensorturtle** [comment]
Hi, it looks like you have a matplotlib related problem.

I think I had this issue once, although I can't remember how I fixed it.
Try following some suggestions in the relevant stackoverflow:
https://stackoverflow.com/questions/55811545/importerror-cannot-load-backend-tkagg-which-requires-the-tk-interactive-fra
